### ISSUE TITLE
Add more Html CSS and  JavaScript effects  to this repository

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/HTML-CSS-JavaScrpt-Animation-Effects#4]
**_if you have some new animation or any javascript effects that help to make a  website awesome pls add it to this repository._**

**Comment by NehaAnand28** [comment]
Hey I would like to add my project in this.

**Comment by Shubham56-droid** [comment]
Sure you can add but pls star this repo and follow me too and thanks for ur contribution
