### ISSUE TITLE
Add more html ,css ,javascript projects

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/HTML-CSS-JavaScrpt-Animation-Effects#5]
Add folder in this repository with HTML CSS javascript

**Comment by Shubham56-droid** [comment]
Add folder in this repository with HTML CSS javascript

**Comment by gauri20pa** [comment]
Can I add my calculator project in this? Please assigned me this.

**Comment by Shubham56-droid** [comment]
yes u can pls do it and star this repo and follow me bro

**Comment by AnushkaSingh1** [comment]
please assign this to me.

**Comment by Shubham56-droid** [comment]
@AnushkaSingh1 you can send ur PR to me and  pls star this repo and follow me
