### ISSUE TITLE
Add a website to this repo made using html css and javascript

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/HTML-CSS-JavaScrpt-Animation-Effects#8]
add  any website like resturant or travel website to this repository

**Comment by AnushkaSingh1** [comment]
please assign this to me, i'll make a webite.

**Comment by Shubham56-droid** [comment]
hi @AnushkaSingh1 Sister u don't need to wait for getting assigned pls send ur pr  i will merge it also star this repo and follow me

**Comment by Shubham56-droid** [comment]
dont forget to star this repository

**Comment by Shubham56-droid** [comment]
you can send me ur PR

**Comment by Shubham56-droid** [comment]
Pull request
