### ISSUE TITLE
Add a landing page for any website

### ISSUE THREAD

**Issue by Shubham56-droid** [Shubham56-droid/HTML-CSS-JavaScrpt-Animation-Effects#9]
Add a landing page of any website using HTML CSS javascript

**Comment by hrshammo** [comment]
Hay, I would like to work on it.

**Comment by Shubham56-droid** [comment]
Sure bro you can send me pr pls star this repo and follow me

**Comment by ritesh423** [comment]
Can i still add a project in this?

**Comment by Shubham56-droid** [comment]
sure

**Comment by Mobasherah12** [comment]
Hi @Shubham56-droid , even I would like to work on this.

**Comment by Shubham56-droid** [comment]
you can  also work on  this issue add as many as landing page u want and pls star this repo and follow me on  github

**Comment by serhatbek** [comment]
Added a Betutor Landing Page #22

**Comment by Shubham56-droid** [comment]
@serhatbek good work bro pls star this repo and follow me ur pr will be merged
